server:
  port: ${PORT:5002}

base-url: /api

spring:
  application:
    name: taskManager

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop